prereq:
  - httpd24-httpd 
  - rh-php73 
  - rh-php73-php 
  - rh-php73-php-mbstring 
  - rh-php73-php-mysqlnd 
  - rh-php73-php-gd 
  - rh-php73-php-xml 
  - mariadb-server 
  - mariadb

db_user: wiki
database_name: wikidata
owner: apache
group: apache